### ISSUE TITLE
Does OIDC auth work for IBM Cloud Kubernetes?

### ISSUE THREAD

**Issue by sunnypatel2141** [kubernetes-client/java#1095]
I was looking at fabric8io/kubernetes-client and it's possible to use create a deployment `client.apps().deployments().inNamespace("default").create(deployment1);`. Reference: https://github.com/fabric8io/kubernetes-client/blob/b4873f45663b811df798f50c36c693ff44b33e1b/doc/CHEATSHEET.md

The reason I'm looking at kubernetes-client is fabric8io doesn't support OIDC id-token, refresh-token. We're using IBM Cloud and in order to access Kubernetes, .kube/config file has fields such as certificate-authority .pem file, id-token as well as refresh-token. 

i.e.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: <path to .pem file>
    server: <server name>
  name: <name>
contexts:
- context:
    cluster: <name>
    namespace: default
    user: <IAM user>
  name: <name>
current-context: <context>
kind: Config
preferences: {}
users:
- name: <IAM user>
  user:
    auth-provider:
      config:
        client-id: kube
        client-secret: kube
        id-token: <id_token>
        idp-issuer-url: https://iam.cloud.ibm.com/identity
        refresh-token: <refresh_token>
      name: oid
```

I believe kubernetes-client supports OIDC but I don't know if it allows deployment provided a yaml file.

Can someone point me in the right direction. Also if they're using OIDC in field, let me know how that's done.

Thanks.
