### ISSUE TITLE
Certificate data not found

### ISSUE THREAD

**Issue by guptamahcl** [kubernetes-client/java#1327]
When calling this from java

`ApiClient apiClient = ClientBuilder.kubeconfig(kubeConfig).build();`

Actual Kubeconfig file:

```
kind: Config
users:
- name: gke_gbu-video-monitoring_us-central1-a_cluster-1552018
  user:
    token: za29.c.Ko8B4AcSB7zcDeDt9CMi-ZN-qVoqn4sIqsNqbCMnMywE72YMdbrTq8gxcbQQe7ajFrsw7ZMyAwOzfQsVpkN6EDqDBGSz0t9M1GMkHa85oX8B8xMGr79Kb0m1aE2DKOpCz_prpW6lr_b9Dv4AJhOmfoAKaNpKEGtQ8gk1QZsYq-EAX6MRCGEmsMpjelpSs3qxTq8
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLekNDQWhPZ0F3SUJBZ0lSQUxIa2U1Q2QwU0UwK2FVTXdsM2VjSDB3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa09UazRZak13TnprdFl6azBOUzAwTkRRMkxXSTFaVFl0TkdVNU5HVXdZV0UwWmpGbQpNQjRYRFRJd01UQXhOREE1TWpjeU5Gb1hEVEkxTVRBeE16RXdNamN5TkZvd0x6RXRNQ3NHQTFVRUF4TWtPVGs0CllqTXdOemt0WXprME5TMDBORFEyTFdJMVpUWXROR1U1TkdVd1lXRTBaakZtTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbGNNUFJDSEFsWjhROG16eEdubmJJcEg1clk3NU9pcTJrd1VEb1VUTQowQzhsaDFNSk85MDh6WUlhdmlMTHpYQVN3RE05Ynlla0VPSWptclBPZWk3TW0vYnJKY1A1Vkw5emY1RlR3MTFYClo0TTFmYXByVS9yVTRDTk9zR2dEVXZoYnd3dS9yOFJCM3JQN0MrZGQ0VUlVT0R4SU5ONHFUVWpyQ2RmUURKZlUKZHRneCtGMjdvL2NQYWRkSW50QUt5WGtZanRHamNXVzE1T2NoVWZ4WUt6ak5GdHhDakRDWVZCYUhDTDhESkdHdApaTlp5MjV2YjNWOG51c1N5QUpydXRGV3FEdTJscCt4ckF1MGdxRDhVOFZOVUd4TEZtaFNGdFJaTzA4NnlNMWdkCmdTR1J0TGFWR2FIRkYyNld3eTNwUzQyK1pXUGV5dFVKVGk3KzdFRFVOUEI0YndJREFRQUJvMEl3UURBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXVVUm56VFJrWE0yMgplWDdhNFdaYldOeEdod2t3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQURqMWdtUEZGaEhyU0JFVnkxQldqSm5qCmEwMFA4VW40TzM5WjZNdU5maWpvKzdubUw1ZnlNQ0FXTWd2ZStxalR3T29DU0FFeDNvZHd4UUVLRzRKbFZYajMKWEZ1ajJWUmlLQmVDdzMxY3p6eVJCYnU4VnlMSDdxL09LTDF4L0gyRnl1RFpOV29vTHdscVFRNTFZUjR4dS9rOApDUVk3ZnN2RW5zR1pvcXNvRlVSbDJPaWFPM3NoNUhFbHJMZ3ZFVG1BSERwS3pYc3cvMDk5TUlKWHQ4Tjd3Z0ZCCjZqTkJEL0gzVG1qc1FQdU9TQ0Y5YVo4V0hYVkxLdHE1d3d1azFGdFlIRzlpa05KVWswU0Z1aC82Mk4xZUVtVFcKelZIdm5lZjZXbmtFUGtTQVYwVDc2Mzl0b291VStXeDhpYWxyZ0ZGaVErcDJjdFFUVnRyUmtqQ2tEdVJ0NE9jPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://1.2.3.4
  name: gke_gbu-video-monitoring_us-central1-a_cluster-1552018
contexts:
- context:
    cluster: gke_gbu-video-monitoring_us-central1-a_cluster-1552018
    user: gke_gbu-video-monitoring_us-central1-a_cluster-1552018
  name: gke_gbu-video-monitoring_us-central1-a_cluster-1552018
current-context: gke_gbu-video-monitoring_us-central1-a_cluster-1552018

```

I am getting below exception:

```
Caused by: java.security.cert.CertificateException: No certificate data found
        at java.base/sun.security.provider.X509Factory.parseX509orPKCS7Cert(X509Factory.java:461) ~[na:na]
        at java.base/sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:361) ~[na:na]
        at java.base/java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:478) ~[na:na]
        at io.kubernetes.client.openapi.ApiClient.applySslSettings(ApiClient.java:1326) ~[client-java-api-10.0.0.jar:na]
        ... 59 common frames omitted
```

The same code works on Windows 10. But does not work on docker image of tomcat `tomcat:9.0.37-jdk11-openjdk`
