### ISSUE TITLE
Having trouble running example

### ISSUE THREAD

**Issue by davidxia** [kubernetes-client/java#143]
I get 403 Forbidden when running Example.java. I tried setting KUBECONFIG to the absolute path of my ~/.kube/config file. I'm able to run `kubectl get pods --all-namespaces`. Is there something I'm missing?

```
null for gcp
Exception in thread "main" io.kubernetes.client.ApiException: Forbidden
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:18462)
	at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:18440)
	at io.kubernetes.client.examples.Example.main(Example.java:40)
```

**Comment by davidxia** [comment]
@lwander, my `~/.kube/config` looks like 

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://35.195.200.26
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-cluster
  name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
- name: my-cluster
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: /Users/dxia/google-cloud-sdk/bin/gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

**Comment by lwander** [comment]
Thanks - I don't think the client fully supports the gcp authenticator (at the very minimum token refresh isn't implemented). It looks like you're running on GKE, so you could try

```bash
gcloud config set container/use_client_certificate True
gcloud container clusters get-credentials my-cluster
```

To get a credential format the client accepts in the meantime.

**Comment by davidxia** [comment]
Yes, I am running the example on a GKE cluster. I ran your commands above. `kubectl get pods --all-namespaces` still works, but Example.java fails with the same error. My `~/.kube/config` now looks like.

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://35.195.200.26
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-cluster
  name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
- name: my-cluster
  user:
    client-certificate-data: ...
    client-key-data: ...
    password: ...
    username: admin
```

**Comment by lwander** [comment]
I've seen this happen for another client library with master version greater than 1.8.0 - I'm not sure what the fix is.

**Comment by davidxia** [comment]
more info. `kubectl version` shows

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.8-gke.0", GitCommit:"a7061d4b09b53ab4099e3b5ca3e80fb172e1b018", GitTreeState:"clean", BuildDate:"2017-10-10T18:48:45Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by brendandburns** [comment]
Can you dump the complete Exception (e.g. `exception.getCode()` `exception.getResponseBody()` that will help determine why authorization is failing.

**Comment by bergman** [comment]
You can get this to work by explicitly calling `registerAuthenticator` like this:
```java
KubeConfig.registerAuthenticator(new GCPAuthenticator());
```

**Comment by davidxia** [comment]
Thanks for the suggestions. I'm running

```java
public class Test {
  public static void main(String[] args) throws Exception {
    KubeConfig.registerAuthenticator(new GCPAuthenticator());
    ApiClient client = Config.defaultClient();
    client.setUsername("dxia");
    Configuration.setDefaultApiClient(client);

    CoreV1Api api = new CoreV1Api();
    try {
      V1PodList list = api.listPodForAllNamespaces(null, null, null, null, null, null, null,
          null, null);
      for (V1Pod item : list.getItems()) {
        System.out.println(item.getMetadata().getName());
      }
    } catch (ApiException e) {
      System.out.println(e);
      System.out.println(e.getCode());
      System.out.println(e.getResponseBody());
    }
  }
}
```

And I get

```
io.kubernetes.client.ApiException: Forbidden
403
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"client\" cannot list pods at the cluster scope: Unknown user \"client\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}
```

I haven't looked too closely at how to set my username. My kubectl makes the following curl command which only have a bearer token. `curl -k -v -XGET  -H "Authorization: Basic TOKEN" -H "User-Agent: kubectl/v1.8
.4 (darwin/amd64) kubernetes/9befc2b" -H "Accept: application/json" https://35.224.232.9/api/v1/pods`

**Comment by bergman** [comment]
@davidxia I'm doing something similar to your code except I don't bother with the username and default api client stuff.

I got credentials using gcloud, like so:
`gcloud container clusters get-credentials my-cluster --zone europe-west1-d --project my-project-12345`

and then this just works:

```java
      KubeConfig.registerAuthenticator(new GCPAuthenticator());

      final CoreV1Api api = new CoreV1Api(Config.defaultClient());

      final int numberOfPods =
          api.listNamespacedPod("default", null, null, null, null, null, null, null, null, null)
              .getItems()
              .size();

      System.out.println("numberOfPods = " + numberOfPods);
```

**Comment by davidxia** [comment]
@bergman Thanks so much.

This now works for me.

```java
    KubeConfig.registerAuthenticator(new GCPAuthenticator());

    final CoreV1Api api = new CoreV1Api(Config.defaultClient());

    final int numberOfPods =
        api.listPodForAllNamespaces(null, null, null, null, null, null)
            .getItems()
            .size();

    System.out.println("numberOfPods = " + numberOfPods);
 ```

`gcloud config list` shows `container/use_v1_api_client = False`. My GKE cluster is regional and version 1.8.4-gke.0. My `~/.kube/config` looked like

```yaml
- name: my-cluster
  user:
    auth-provider:
      config:
        access-token: ...
        cmd-args: config config-helper --format=json
        cmd-path: /Users/dxia/google-cloud-sdk/bin/gcloud
        expiry: 2018-01-05T16:44:44Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
