### ISSUE TITLE
Getting Namespace from Current Context...?

### ISSUE THREAD

**Issue by allen-servedio** [kubernetes-client/java#145]
Hi,

It appears that Kubernetes allows you to define a namespace within a context: https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/ :

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: fake-ca-file
    server: https://1.2.3.4
  name: development
- cluster:
    insecure-skip-tls-verify: true
    server: https://5.6.7.8
  name: scratch
contexts:
- context:
    cluster: development
    namespace: frontend
    user: developer
  name: dev-frontend
- context:
    cluster: development
    namespace: storage
    user: developer
  name: dev-storage
- context:
    cluster: scratch
    namespace: default
    user: experimenter
  name: exp-scratch
current-context: ""
kind: Config
preferences: {}
users:
- name: developer
  user:
    client-certificate: fake-cert-file
    client-key: fake-key-file
- name: experimenter
  user:
    password: some-password
    username: exp
```

I might be overlooking something, but I do not see a way to retrieve this value short of reading in the config file myself and extracting it (which I can do, but...). Is there  an existing way to get this namespace that I have overlooked?

We are going to be accessing multiple contexts from our service and would like to pull this information from the Context if possible.

Thanks!
Allen
