### ISSUE TITLE
Error from server: failed to create typed patch object

### ISSUE THREAD

**Issue by saparaj** [kubernetes-client/java#1492]
Hi K8s Team,

I am getting below error when I am trying to execute: 
kubectl apply --server-side=true --field-manager=kubectl -f nginx.yml

Cluster Version: 1.18.10
Error from server: failed to create typed patch object: .spec.template.spec.containers[name="nginx"].ports: element 0: associative list with keys has an element that omits key field "protocol"

I am getting same error if I use method from client-java-extended library.
Kubectl.apply(V1Deployment.class).fieldManager("kubectl").forceConflict(true).resource((V1Deployment) resource).execute();

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
```

**Comment by brendandburns** [comment]
Your Port in the container resource needs to have a protocol (TCP or UDP)

**Comment by brendandburns** [comment]
```yaml
...
ports:
- containerPort: 80
  protocol: TCP
```
