### ISSUE TITLE
cp: can't stat '/xxxxxx/gen/src/main/java/io/k8s/xxxxxx': No such file or directory`

### ISSUE THREAD

**Issue by niaomingjian** [kubernetes-client/java#1496]
Following the latest document https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md#example-commands-for-local-crd-manifests to generate java class models with my custom CRD encountered the error "cp: can't stat '/xxxxxx/gen/src/main/java/io/k8s/xxxxxx': No such file or directory`" which was similar to https://github.com/kubernetes-client/java/issues/1253.

Sample CRD with this kind of problem:

````
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.yy.k8s.io
spec:
  group: yy.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            cronSpec:
              type: string
            image:
              type: string
            replicas:
              type: integer
````

When changed the `.spec.group` from yy.**k8s**.io to yy.**k9s**.io and executed that docker run command with `-n io.k9s.yy`, it could generate the model classes successfully. Looks like we can not define `group` as `*.k8s.io`. Is it a particular design so we can't define this kind of `group`? If yes, docs had better note this case. If not, it may be an issue.
