### ISSUE TITLE
NullPointer Exception using Kubectl.apply from client-java-extended

### ISSUE THREAD

**Issue by saparaj** [kubernetes-client/java#1519]
Hello @brendanburns and @yue9944882,

I am trying to create an ingress using Kubectl.apply as per this: https://github.com/kubernetes-client/java/blob/b0c91798c63203f20dc8f2674197e772b2c187ee/docs/kubectl-equivalence-in-java.md#kubectl-apply
My Kubernetes cluster version: 1.18.10 and java-client version: 10.0.0
```
Kubectl.apply(NetworkingV1beta1Ingress.class).resource(resource).execute();
```
I am getting below error:
Exception in thread "main" java.lang.NullPointerException
	at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.getGenericApi(Kubectl.java:259)
	at io.kubernetes.client.extended.kubectl.Kubectl$ResourceBuilder.getGenericApi(Kubectl.java:293)
	at io.kubernetes.client.extended.kubectl.KubectlApply.executeServerSideApply(KubectlApply.java:73)
	at io.kubernetes.client.extended.kubectl.KubectlApply.execute(KubectlApply.java:67)

I tried the same resource with kubectl CLI and I don't see any error:
kubectl apply -f /Users/saparaj/k8s-official-java-client-server-apply/resources/ingress.yml --server-side
ingress.networking.k8s.io/myapp-prod serverside-applied

ingress.yaml
```
# Ingress service for production
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myapp-prod
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: myapp
spec:
  rules:
    - host: test.canary.com
      http:
        paths:
          - backend:
              serviceName: myapp-prod
              servicePort: 8088
```
Please let me know if I am missing something here.

Thanks,
Swarda
