### ISSUE TITLE
java.security.UnrecoverableKeyException when using password protected keystore

### ISSUE THREAD

**Issue by agr-priyanshu** [kubernetes-client/java#1539]
The client connection to target K8S cluster fails with java.security.UnrecoverableKeyException error when JVM is using password protected keystore. When tried removing the password protection from keystore; it worked like a charm.

Is this option not supported or I am missing something in configuration?

Error Message :
`java.security.UnrecoverableKeyException: Get Key failed: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.\n\tat java.base/sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:462)\n\tat java.base/sun.security.util.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:90)\n\tat java.base/java.security.KeyStore.getKey(KeyStore.java:1057)\n\tat java.base/sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:145)\n\tat java.base/sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)\n\tat java.base/javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:271)\n\tat io.kubernetes.client.util.SSLUtils.keyManagers(SSLUtils.java:67)\n\tat io.kubernetes.client.util.credentials.ClientCertificateAuthentication.provide(ClientCertificateAuthentication.java:49)\n\tat io.kubernetes.client.util.credentials.KubeconfigAuthentication.provide(KubeconfigAuthentication.java:52)\n\tat io.kubernetes.client.util.ClientBuilder.build(ClientBuilder.java:329)\n\tat io.kubernetes.client.util.Config.fromConfig(Config.java:97)\n\tat `

**Comment by sarveshkaushal** [comment]
Looks like a problem with your key that you are supplying to keystore. But could you provide more information on how to repro this with code snippet? Please redact any sensitive information.

**Comment by agr-priyanshu** [comment]
I am using the example mentioned here;
[KubeConfigFileClientExample.java](https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java)

Here is my Kubeconfig file
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <certificate_authority_content>
    server: https://<APIServer>:443
  name: TestAKS
contexts:
- context:
    cluster: TestAKS
    user: clusterUser_TestAKS
  name: TestAKS
current-context: TestAKS
kind: Config
preferences: {}
- name: clusterUser_TestAKS
  user:
    client-certificate-data: <client_certificate_content>
    client-key-data: <client_key_content>
    token: <token>
```
The only difference I have in the setup is that in my JVM; I am not using the default keystore. I have a custom keystore which is password protected like below;
```
-Djavax.net.ssl.trustStore=<trustStorePath>/castore.p12 
-Djavax.net.ssl.trustStorePassword=testtrust 
-Djavax.net.ssl.trustStoreType=PKCS12 
-Djavax.net.ssl.keyStore=<keyStorePath>/keystore.p12 
-Djavax.net.ssl.keyStorePassword=testkey
-Djavax.net.ssl.keyStoreType=PKCS12
 ```

If I take it out then it works fine.
