### ISSUE TITLE
V1EnvVar value is always String even though YAML can have numeric value. Prevents proper use of server-side dry run

### ISSUE THREAD

**Issue by davidxia** [kubernetes-client/java#1649]
**Describe the bug**

I'm trying to use `AppsV1Api.createNamespacedDeployment()` [1] with the `dryRun` parameter set to `All`. I have a YAML manifest for a Deployment with a Container with a numeric env var like so (full YAML below).

```
- name: SOME_VAR
  value: 1
```

K8s doesn't allow env vars with non-string values. As expected, `kubectl apply -f deployment.yaml --dry-run=server` fails.

```
Error from server (BadRequest): error when creating "deployment.yaml": Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Lifecycle: Image: Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 1, error found in #10 byte of ...|,"value":1}],"image"|..., bigger context ...|my-deployment"},{"name":"SOME_VAR","value":1}]...
```

I first deserialize the YAML from a String into an ObjectNode, then convert that to a `V1Deployment` [2] object like so.

```java
import com.fasterxml.jackson.databind.node.ObjectNode;
...
private static final YAMLFactory YAML_FACTORY = new YAMLFactory();
private static final YAMLMapper YAML_MAPPER = new YAMLMapper();

  public static List<ObjectNode> read(final String content) throws IOException {
    return YAML_MAPPER
        .readValues(YAML_FACTORY.createParser(content), OBJ_NODE_REF)
        .readAll()
        .stream()
        .map(rawYaml -> (ObjectNode) rawYaml)
        .collect(Collectors.toList());
  }

      Yaml.read(manifests)
          .forEach(
              yml -> {

   final V1Deployment deployment = io.kubernetes.client.util.Yaml.loadAs(yml.toString(), V1Deployment.class);
      }

        appsV1Api.createNamespacedDeployment("my-namespace", deployment, "true", "All", "metadata.name=my-deployment");
```

The last line should throw an `ApiException` like `kubectl`. It doesn't because `Yaml.loadAs` silently converts the env var's value of 1 from an `com.fasterxml.jackson.databind.node.IntNode` to the String type in `V1EnvVar` [2]. The server-side dry run succeeds.

**How should numeric env var values be handled by this client library?**

** Client Version **
1.18.15

** Kubernetes Version **
1.18.16-gke.1200

** Java Version **
11.0.10

**To Reproduce**

Save the following YAML as deployment.yaml. `kubectl apply -f deployment.yaml --dry-run=server` fails.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
        - name: my-container
          image: $DEPLOYMENT_IMAGE
          env:
            # Invalid kubernetes yaml
            - name: SOME_VAR
              value: 1
```

Use the Java snippet above to repro the sucessful server-side dry run call with this client library.

**Expected behavior**
Converting an env var whose value is com.fasterxml.jackson.databind.node.IntNode into a V1EnvVar should preserve the type for correct dry run validation.

[1]: https://github.com/kubernetes-client/java/blob/f20788272291c0e79a8c831d8d5a7dd94d96d2de/kubernetes/docs/AppsV1Api.md#createNamespacedDeployment
[2]: https://github.com/kubernetes-client/java/blob/f20788272291c0e79a8c831d8d5a7dd94d96d2de/kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1EnvVar.java#L34
