### ISSUE TITLE
Apply failed: reason: Unexpected unknown resource type: class io.kubernetes.client.openapi.models.NetworkingV1beta1Ingress

### ISSUE THREAD

**Issue by saparaj** [kubernetes-client/java#1668]
Hello Team,
If I try kubectl server side apply with below ingress against my cluster, it works
```
# Ingress service for production
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myapp-prod
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: myapp
spec:
  rules:
    - host: test.canary.com
      http:
        paths:
          - backend:
              serviceName: myapp-prod
              servicePort: 8088
```
kubectl apply -f ingress.yml --server-side
ingress.networking.k8s.io/myapp-prod serverside-applied

But if I try kubectl apply method from java client extended library, it does not work and I get below message:
Apply failed: reason: Unexpected unknown resource type: class io.kubernetes.client.openapi.models.NetworkingV1beta1Ingress

Can you please help me figure out why its not working from code?

Java Client Version
12.0.0

Kubernetes Version
1.18.10

Java Version
Java 8

Thanks,
Swarda

**Comment by brendandburns** [comment]
The ModelMap isn't initializing correctly.

This may be related to https://github.com/kubernetes-client/java/issues/1659 if you are running in a fat jar.

Calling `ModelMap.InitModelMap()` before you make any calls to apply should fix things.

**Comment by saparaj** [comment]
I tried ModelMap.refresh(...) and it did not work.
If I upgrade my cluster to 1.19.7 then networking.k8s.io/v1beta1 and networking.k8s.io/v1 Ingress apply both are working. 

I am seeing this issue with Kubernetes Cluster Version: 1.18.10 where networking.k8s.io/v1beta1 and networking.k8s.io/v1 Ingress don't work, networking.k8s.io/v1 should only work above 1.19 version (https://kubernetes.io/docs/concepts/services-networking/ingress/) so that's expected.
Wanted to know why networking.k8s.io/v1beta1 ingress doesn't work with same code. Code is same as of this: https://github.com/kubernetes-client/java/issues/1652

Thanks,
Swarda

**Comment by saparaj** [comment]
Debugging File: 
[debuggingIngress.txt](https://github.com/kubernetes-client/java/files/6425235/debuggingIngress.txt) attached.

**Comment by saparaj** [comment]
Hi @brendanburns and @yue9944882,

Any update on this?

Thank you,
Swarda

**Comment by Smith334** [comment]
Hi

I am attempting to apply the calico-operator yaml using the 'kubernetes java client' and it is resulting in a similar exception being thrown. 

"io.kubernetes.client.extended.kubectl.exception.KubectlException: Unexpected unknown resource type: class io.kubernetes.client.openapi.models.V1beta1PodSecurityPolicy"

I have done some testing and have narrowed the exception down to coming from line 4862 in the calico-operator.yaml for that PodSecurityPolicy. 

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: tigera-operator
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  volumes:
  - 'hostPath'
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  # Assume that persistentVolumes set up by the cluster admin are safe to use.
  - 'persistentVolumeClaim'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false

```

When I apply it through the command line with "kubectl apply -f <file.yaml>" it has no problem applying and throws no exception, but when applying it with the Kubernetes Java client I get that exception. Unfortunately, I cannot rely on using scripts to apply it through the command line and therefore need the java client working.

Are there any thoughts as to why this is happening, and what can be done to fix it?

I have attached the yaml I am trying to apply. You can also find it here: 
`https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/master/calico-operator.yaml`

[calico-operator.yaml.txt](https://github.com/kubernetes-client/java/files/8698502/calico-operator.yaml.txt)


Kubernetes Java Client Version
14.0.1

Kubernetes Java Client Extended Version
15.0.1

Kubernetes Version
1.2.1

AWS Java SDK
2.17.46

Java Version
Java 8
