### ISSUE TITLE
createNamespacedService is not working for spec type (NodePort,LoadBalancer).

### ISSUE THREAD

**Issue by Rajnishcsk** [kubernetes-client/java#203]
createNamespacedService is working fine for this yaml.
```
kind: Service
apiVersion: v1
metadata:
  name: myservices
spec:
  ports:
    - name: http
      port: 8088
      targetPort: 8088
  selector:
      app: nginx
```
after adding any spec type like NodePort or LoadBalancer getting error:
```
kind: Service
apiVersion: v1
metadata:
  name: myservices
spec:
  ports:
    - name: http
      port: 8088
      targetPort: 8088
  selector:
      app: nginx
  type: LoadBalance

>  io.kubernetes.client.ApiException: Unprocessable Entity
