### ISSUE TITLE
Forbidden: may only update PVC status

### ISSUE THREAD

**Issue by jawad846** [kubernetes-client/java#2180]
I installed the EFS CSI driver to mount EFS on EKS, I followed [Amazon EFS CSI driver](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html).

I've faced the below error while deploying PersistentVolumeClaim.

```
Error from server (Forbidden): error when creating "claim.yml": persistentvolumeclaims "efs-claim" is forbidden: may only update PVC status
```

StorageClass.yaml -->

``` 
   kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: efs-sc
    provisioner: efs.csi.aws.com
    mountOptions:
      - tls  
  ```

pv.yaml -->

``` 
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: efs-pv
    spec:
      capacity:
        storage: 5Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      storageClassName: efs-sc
      csi:
        driver: efs.csi.aws.com
        volumeHandle: fs-xxxxxxxxxxx 

```

pvclaim.yaml -->

``` 
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: efs-claim
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: efs-sc
      resources:
        requests:
          storage: 5Gi
      selector:
        matchLabels:
          name: production-environment
          role: prod 
```

Kindly help me to resolve this

**Comment by brendandburns** [comment]
Are you using this Java client? It appears that you are using `kubectl`?

Regardless, the error is caused by the persistent volume claim already existing. Only the `status` sub-resource in the `PersistentVolumeClaim` resource can be modified once it is created.

**Comment by jawad846** [comment]
I fixed the issue with aws support.

Posting the resolution might help someone.

We removed the `system:nodes` ands `system:bootstrappers` permission of the controller server from the aws-auth configmap. and it's fixed the issue.

Previous  configmap/aws-auth -->

```
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::xxxxxxxxxx:role/eksctl-sc-prod-eks-cluster-NodeInstanceRole-T3B32A19KBZB
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
        - system:bootstrappers
        - system:nodes
        - system:masters
      rolearn: arn:aws:iam::xxxxxxxxx:role/sc-prod-iam-ec2-instance-profile-bastion
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::xxxxxxxxxx:user/jawad846
      username: admin
      groups:
        - system:masters
```

Currenlt configmap/aws-auth -->

```
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::xxxxxxxxx:role/eksctl-sc-prod-eks-cluster-NodeInstanceRole-T3B32A19KBZB
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::xxxxxxxxxx:role/sc-prod-iam-ec2-instance-profile-bastion
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::xxxxxxxxxx:user/jawad846
      username: admin
      groups:
      - system:masters

```

Thanks @all
