### ISSUE TITLE
Apply failed: Unexpected unknown resource type: class io.kubernetes.client.openapi.models.V1beta1PodSecurityPolicy

### ISSUE THREAD

**Issue by Smith334** [kubernetes-client/java#2251]
Hi, I commented this on another issue but thought I would create a new issue in case it is a part of a larger issue.

I am attempting to apply the calico-operator yaml using the 'kubernetes java client' and it is resulting in a similar exception being thrown. 

"io.kubernetes.client.extended.kubectl.exception.KubectlException: Unexpected unknown resource type: class io.kubernetes.client.openapi.models.V1beta1PodSecurityPolicy"

I have done some testing and have narrowed the exception down to coming from line 4862 in the calico-operator.yaml for that PodSecurityPolicy. 

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: tigera-operator
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  volumes:
  - 'hostPath'
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  # Assume that persistentVolumes set up by the cluster admin are safe to use.
  - 'persistentVolumeClaim'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false

```

When I apply it through the command line with "kubectl apply -f <file.yaml>" it has no problem applying and throws no exception, but when applying it with the Kubernetes Java client I get that exception. Unfortunately, I cannot rely on using scripts to apply it through the command line and therefore need the java client working.

Are there any thoughts as to why this is happening, and what can be done to fix it?

I have attached the yaml I am trying to apply. You can also find it here: 
`https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/master/calico-operator.yaml`

[calico-operator.yaml.txt](https://github.com/kubernetes-client/java/files/8698721/calico-operator.yaml.txt)

Kubernetes Java Client Version
14.0.1

Kubernetes Java Client Extended Version
15.0.1

Kubernetes Version
1.2.1

AWS Java SDK
2.17.46

Java Version
Java 8
