### ISSUE TITLE
NullPointerException when ClientBuilder.kubeconfig(kubeconfigfile)

### ISSUE THREAD

**Issue by pawank0411** [kubernetes-client/java#2344]
Hi Team,

I am facing an issue while building the ApiClient using config file which is placed in the path specified by the [Kube Config documentation](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/).
**Path : /.kube/config**

Exception I am getting while accessing `ClientBuilder.kubeconfig(kubeconfigfile)` : 
```
java.lang.NullPointerException: null at io.kubernetes.client.util.ClientBuilder.kubeconfig(ClientBuilder.java:288) at
org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) at org.springframework.aop.framework.CglibAopProxySCglibMethodInvocation.invoke Joinpoint (CglibAopProxy.java:793) at
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) at
org.springframework.aop.aspectj.MethodInvocationProceeding JoinPoint.proceed(MethodInvocationProceeding JoinPoint.java:89) at sun.reflect.GeneratedMethodAccessor177.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.aop.aspectj.AbstractAspect...
.....

```

On logging the kubeconfig file
kubeconfig.getServers() - null
kubeconfig.getCluster() - I am getting a cluster object where the server field is populated.

Not sure why getServers() is null due to which I am getting the above exception.

------------------------------------------------------------------------
KubeConfig File:
```
apiVersion: v1
kind: Config
clusters:
 - cluster:
	certificate-authority-data:MNSNDKDKDK....
	server: https://10.3.0.2
   name: <name>
users:
 - name: <service_account>
contexts:
 - context:
	cluster: <cluster>
	user: <service_account>
	namespace: <namespace>
   name: <name>
current-context: <context>
```
