### ISSUE TITLE
Failing to create Custom Object APIException:Not Found

### ISSUE THREAD

**Issue by roksolana-d** [kubernetes-client/java#464]
I am trying to create custom object defined in the yaml file. However, I get an `API Exception: Not Found` error. What might be the reason of it? Could it be the api version problem?

Here is how I read the file and create an object from it:

```
  def convertYamlToObject()= {
    val input = new FileInputStream(new File("yamlFilePath"))
    val yaml: Yaml = new Yaml
    val data: Object = yaml.load(input)
    data
  }

  def create(): Unit = {
    val body = convertYamlToObject()
    val sparkAppCreation = apiInstance.createNamespacedCustomObject("sparkoperator.k8s.io", "v1alpha1", "default", "sparkapplications", body,"true")
    println(sparkAppCreation)
}
```

And this is a yaml file I have defined:
```
apiVersion: sparkoperator.k8s.io/v1alpha1
kind: SparkApplication
metadata:
  name: spark-example
  namespace: default
spec:
  type: Scala
  image: gcr.io/ynli-k8s/spark:v2.4.0
  mainClass: org.apache.spark.examples.SparkExample
  mainApplicationFile: http://localhost:port/file.jar
  mode: cluster
  deps: {}
  driver:
    coreLimit: 1000m
    cores: 0.1
    labels:
      version: 2.4.0
    memory: 1024m
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    labels:
      version: 2.4.0
    memory: 1024m
  imagePullPolicy: Never
  restartPolicy: Never
```
UPDATE: I have installed Spark operator with Helm
