### ISSUE TITLE
Custom Object status constantly returns null

### ISSUE THREAD

**Issue by roksolana-d** [kubernetes-client/java#475]
I've been trying to get the statuses of the custom object. For that, I have created a watch on the custom object and tried to print the status of this object, however, I've got a NullPointerException when I try to return the status, the output shows null even when the type field value changes. This is how it looks in code:

```
val watchCustomObjects: Watch[V1Namespace]  = Watch.createWatch(apiClient, apiInstance.getNamespacedCustomObjectCall(group,version,  namespace, plural, name, null, null), new TypeToken[Watch.Response[V1Namespace]]{}.getType)
    while(watchCustomObjects.hasNext){
      println("Type: " + watchCustomObjects.next().`type`)
    }

```
When I describe this custom object using kubectl I can see all the events changes:
```
Status:
  Application State:
    Error Message:  
    State:          FAILED
Events:
  Type     Reason                     Age                From            Message
  ----     ------                     ----               ----            -------
  Normal   SparkApplicationAdded      69s                spark-operator  SparkApplication spark-example was added, Enqueuing it for submission
  Normal   SparkApplicationSubmitted  65s                spark-operator  SparkApplication spark-example was submitted successfully
  Normal   SparkDriverPending         65s (x2 over 65s)  spark-operator  Driver spark-example-driver is pending
  Normal   SparkDriverRunning         62s (x2 over 63s)  spark-operator  Driver spark-example-driver is running
  Warning  SparkDriverFailed          56s                spark-operator  Driver spark-example-driver failed
  Warning  SparkApplicationFailed     56s                spark-operator  SparkApplication spark-example terminated with state: FAILED
```
For some reason, I cannot output any of the custom object statuses and other relevant information, like message, reason and so on. Is there any way to fix it?

**Comment by roksolana-d** [comment]
Still when I try to output the status the result is displayed like this:

`Type: null`

**Comment by brendandburns** [comment]
That's not Java code (is it Closure?) I'm not familiar enough with Closure to guess what could be going wrong here. Can you try building a pure Java snippet?

**Comment by roksolana-d** [comment]
It's Scala. In Java it would look like this, I suppose:

```
Watch<V1Namespace> watchCustomObjects = Watch.createWatch(apiClient, apiInstance.getNamespacedCustomObjectCall(group,version,  namespace, plural, name, null, null), new TypeToken<Watch.Response<V1Namespace>>{}.getType())
    while(watchCustomObjects.hasNext){
      println("Type: " + watchCustomObjects.next().`type`)
    }
```

**Comment by ancientsea** [comment]
@roksolana-d I think you're trying to use this client to invoke spark-k8s-operator APIs in Scala, right? Does it work?

**Comment by roksolana-d** [comment]
@ancientsea Yes, that's right. Java client works but there is this Status problem, which for some reason constantly returns null

**Comment by ancientsea** [comment]
@roksolana-d  Are you using the `createNamespacedCustomObject` from the `CustomObjectsApi` class? Can I know the the input arguments you used to create an sparkApplication? Thanks.

**Comment by roksolana-d** [comment]
@ancientsea yes, I used this class. The configuration looks like this:

```
val customObjectBody = convertYamlToJson(sparkAppFile)
 val sparkAppCreation = apiInstance.createNamespacedCustomObject("sparkoperator.k8s.io", "v1alpha1", "default", "sparkapplications", customObjectBody,"false")
```

**Comment by ancientsea** [comment]
> @ancientsea yes, I used this class. The configuration looks like this:
> 
> ```
> val customObjectBody = convertYamlToJson(sparkAppFile)
>  val sparkAppCreation = apiInstance.createNamespacedCustomObject("sparkoperator.k8s.io", "v1alpha1", "default", "sparkapplications", customObjectBody,"false")
> ```

@roksolana-d Thanks!!! 

I am also interested in the `customObjectBody` here. Is the input `sparkAppFile` the whole part as the https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi.yaml file if we talk about the spark-pi example? And not just the `spec` part? Or something else? 

Thanks.

**Comment by roksolana-d** [comment]
Ok, custom object body looks like this:

```
apiVersion: sparkoperator.k8s.io/v1alpha1
kind: SparkApplication
metadata:
  name: spark-example
  namespace: default
spec:
  type: Scala
  image: gcr.io/ynli-k8s/spark:v2.4.0-SNAPSHOT
  mainClass: example.SparkExample
  mainApplicationFile: http://192.168.99.100:8089/spark_k8s_airflow_param.jar
  mode: cluster
  arguments:
    - http://192.168.99.100:8089/jar_test_data.txt
  driver:
    coreLimit: 1000m
    cores: 0.1
    labels:
      version: 2.4.0
    memory: 1024m
    serviceAccount: default
  executor:
    cores: 1
    instances: 1
    labels:
      version: 2.4.0
    memory: 1024m
  imagePullPolicy: Always
```
