### ISSUE TITLE
GCP NullPointerException when trying to read ~/.kube/config file, on expiry field

### ISSUE THREAD

**Issue by AttwellBrian** [kubernetes-client/java#559]
My `~/.kube/config` contains the following

```
- name: gke_css-prod_us-west2_services-staging-cluster
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: /Users/brianattwell/Downloads/google-cloud-sdk/bin/gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

When `GCPAuthenticator` tries to parse this file, it crashes because there is no `expiry` field. I'm using version 4.0.0 of the client.

I generate the config by running the following:

```
gcloud config set project css-prod
gcloud container clusters get-credentials <cluster> --region us-west2 --project <project> --internal-ip
```
