### ISSUE TITLE
Forbidden: may only update PVC status

### ISSUE THREAD

**Issue by pattyphonemany691** [kubernetes-client/java#716]
In trying to create Persistent Volume Claim, I get a ` is forbidden: may only update PVC status` error.
```
V1ObjectMeta pvcMetadata = new V1ObjectMetaBuilder().withName(pvcName).withNamespace(mynamespace).build();
V1PersistentVolumeClaimSpec pvcSpec = getVolumeClaimSpec(); // Spec defined with access modes, resources, and node selector
V1PersistentVolumeClaim pvc = V1PersistentVolumeClaimBuilder().withMetadata(pvcMetadata).withSpec(pvcSpec).build();
```
Debug logging:
```
--> POST https://endpoint/api/v1/namespaces/mynamespace/persistentvolumeclaims HTTP/1.1
Accept: application/json
User-Agent: Swagger-Codegen/1.0-SNAPSHOT/java

{"metadata":{"name":"pvc-name","namespace":"mynamespace"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"","volumeMode":"Filesystem","volumeName":"pv-name"}}
```
```
- HTTP/1.1 403 Forbidden (50ms)
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"persistentvolumeclaims \"pvc-name\" is forbidden: may only update PVC status","reason":"Forbidden","details":{"name":"pvc-name","kind":"persistentvolumeclaims"},"code":403}
```

I've confirmed that I have permissions to create the PVC.
I'm also able to create other resources in the cluster. 

I've tried using the 5.0.0 and 6.0.1 builds of the kubernetes java client.
Unfortunately I'm unable to find much detail about this error. However, I did stumble upon https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/noderestriction/admission.go#L143 and see that it's associated with the node restriction admission controller. From my understanding node restriction is enabled by default for node using EKS. I'm also unsure if this what is causing the above error.

Could I get some guidance on how to move forward? Is there additional logging that can be added to better understand what's going on?

**Comment by brendandburns** [comment]
you need to do the POST to 

`https://endpoint/api/v1/namespaces/mynamespace/persistentvolumeclaims/status`

Note the `/status` at the end.

(I agree the error message isn't great)

To do this, I believe the `CoreV1.replaceNamespacedPersistentVolumeClaimStatus` function will do what you want.

**Comment by pattyphonemany691** [comment]
Unfortunately, the same error is still being thrown.
I've tried the following:

1. Creating a `V1PersistentVolumeClaim` with the status field set before calling `createNamespacedPersistentVolumeClaim` and then running `CoreV1.replaceNamespacedPersistentVolumeClaimStatus`
2. Setting the status field after creating a `V1PersistentVolumeClaim` by calling `createNamespacedPersistentVolumeClaim`, then running `CoreV1.replaceNamespacedPersistentVolumeClaimStatus`
3. If I try to just past the `V1PersistentVolumeClaim` to `CoreV1.replaceNamespacedPersistentVolumeClaimStatus` this fails due to a `forbidden: unexpected operation \"CREATE\"` error. I think this makes sense since the replace makes a `PUT` operation and it expects that the object was already created with a previous `POST` call. 
4. I also thought it was because I was throwing a hard exception instead of catching it and it was actually being created in the background ,similar to what's observed in https://github.com/kubernetes-client/java/issues/86, but no dice; the PVC isn't created in the namespace.

**Comment by pattyphonemany691** [comment]
We believe the problem was caused by our configuration, which was designated as a `system:node`, and it was not permitted to create a PVC.

Thanks for your help!

**Comment by afahmy11** [comment]
> We believe the problem was caused by our configuration, which was designated as a `system:node`, and it was not permitted to create a PVC.
> 
> Thanks for your help!

hi pattyphonemany691 
what was the exact fix you applied?

**Comment by pattyphonemany691** [comment]
@afahmy11 atthe time, we found that the `NodeRestriction` admission controller preveneted `system:node`s from creating PVCs. https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/noderestriction/admission.go#L156

**Comment by jawad846** [comment]
@pattyphonemany691, could you pls help what to do here. I'm using AWS EKS. I'm getting the same error

`Error from server (Forbidden): error when creating "claim.yml": persistentvolumeclaims "efs-claim-ro" is forbidden: may only update PVC status`

**Comment by jawad846** [comment]
I installed the EFS CSI driver to mount EFS on EKS, I followed [Amazon EFS CSI driver](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html).

I've faced the below error while deploying PersistentVolumeClaim.

```
Error from server (Forbidden): error when creating "claim.yml": persistentvolumeclaims "efs-claim" is forbidden: may only update PVC status
```


StorageClass.yaml -->

``` 
   kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: efs-sc
    provisioner: efs.csi.aws.com
    mountOptions:
      - tls  
  ```

pv.yaml -->

``` 
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: efs-pv
    spec:
      capacity:
        storage: 5Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      storageClassName: efs-sc
      csi:
        driver: efs.csi.aws.com
        volumeHandle: fs-xxxxxxxxxxx 

```

pvclaim.yaml -->

``` 
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: efs-claim
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: efs-sc
      resources:
        requests:
          storage: 5Gi
      selector:
        matchLabels:
          name: production-environment
          role: prod 
```

Kindly help me to resolve this
