### ISSUE TITLE
Allow custom values in Secret data and Quantity fields

### ISSUE THREAD

**Issue by BartXZX** [kubernetes-client/java#817]
We are currently using the client to generate Kubernetes yaml files. In the generated yaml files we would like to have placeholders we can substitute later on in our processes.

However the Secret data and Quantity fields do not allow arbitrary values in the fluent builder. Data for example expects a byte array, which I understand, but in my case I do not want to directly apply the yamls, but rather do some more processing before I apply them. For example:

```java
new V1SecretBuilder()
                .withApiVersion("v1")
                .withKind("Secret")
                .withNewMetadata()
                .withName("my-secret")
                .withNamespace("${my.namespace}")
                .endMetadata()
                .withType("generic")
                .addToData("my.crt", "${my.certificatefile}"); //Compile error.
                .build();
```

The generated yaml (should) look like this:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: ${my.namespace}
type: generic
data:
  my.crt: ${my.certificatefile}
```

I am currently using an ugly workaround where I use 'stringData', and search and replace it with 'data' after the yamls are generated.

Do you guys know the best way to get this to work?
