### ISSUE TITLE
How to deal with custom fields in volumn

### ISSUE THREAD

**Issue by wangyushuai** [kubernetes-client/java#822]
for example,  custom fields in volumn -- jdcloudElasticBlockStore,  how to deal  when   creating  namespace deployment
```
  volumes:
    - name: pv-static
      jdcloudElasticBlockStore:
        volumeID: vol-ogcbkdjg7x 
```
