### ISSUE TITLE
There are multiple Kind in a Yaml file, how to perform this case using kubernetes-client?

### ISSUE THREAD

**Issue by wangyushuai** [kubernetes-client/java#835]
I want to  create  multiple resource in a yaml by once request, how  can I do ?

Thanks!

**Comment by wangyushuai** [comment]
@brendandburns   @yue9944882

**Comment by brendandburns** [comment]
This isn't easy to do. You would need to create the raw HTTP path (e.g. `/api/v1/pods/...` from the object's `kind` and `apiGroup`)

We should probably write a utility function to make this easier.

**Comment by wangyushuai** [comment]
> sy to do. You would need to create the raw HTTP path (e.g. `/api/v1/pods/...` from the object's `kind` and `apiGroup`)
> 
> We should probably write a utility function to make this easier.

@brendanburns 

I think I may not express what I mean, for example:

```
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress 
  namespace: nginx-ingress
```
If i want to execute this yaml , how i can  do it in once request by using  client.  And can you show you code ? 
Thanks !!
