### ISSUE TITLE
create job without exception but CAN NOT find by kubectl it is seem like not correct

### ISSUE THREAD

**Issue by tain198127** [kubernetes-client/java#846]
software  environment ：
 > minikube:1.5.2
 > jdk:1.8
> kubectl:v1.16.3
>gradle:
```gradle
compile group: 'io.kubernetes', name: 'client-java', version: '6.0.1'
```

hardware environment:
> mac book pro

This is the yaml config
``` yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: process-item-1
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: jobexample
      labels:
        jobgroup: jobexample
    spec:
      containers:
        - name: c
          image: busybox
          command: ["sh", "-c", "echo Processing item $ITEM && sleep 5"]
      restartPolicy: Never

```

and my java code below
``` java
        V1Job job = (V1Job) Yaml.load(yamlContent);

        ApiClient client = connect(experiment);

        BatchV1Api batchV1Api = new BatchV1Api(client);

        V1Job createdJob = batchV1Api.createNamespacedJob("default",job,"true","All","");
        log.info("create job[{}]\n",createdJob);

        V1JobList list = batchV1Api.listNamespacedJob("default","true","","",null,100,null,100, false);
        if(list != null && list.getItems()!= null && !list.getItems().isEmpty()){
            log.info(list.getItems().get(0));
        }
        return true;
```

I got no error or exception, but I CAN NOT find the job in kubectl by command
```cmd
kubectl get job
```
