### ISSUE TITLE
Refresh token not written to kube.conf correctly

### ISSUE THREAD

**Issue by mlbiam** [kubernetes-client/java#870]
While implementing #855 i found that the hashmap returned by the `refresh` method in the `Authenticator` interface.  The new token is used on the existing integration, but subsequent requests fail.  Here's an example of a "correct" kube config:

```
apiVersion: v1
clusters:
- cluster:
    server: https://k8sapi.apps.tremolo.io
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: mboorshtein
  name: kubernetes
current-context: kubernetes
kind: Config
preferences: {}
users:
- name: mboorshtein
  user:
    auth-provider:
      config:
        client-id: kubernetes
        id-token: XXXXXXX
        idp-issuer-url: https://XXXXXX/auth/idp/k8sIdp
        refresh-token: XXXXXXX
      name: oidc
```

What the java client generates after a refresh:

```
preferences: {}
apiVersion: v1
kind: Config
current-context: kubernetes
contexts:
- context: {cluster: kubernetes, user: mboorshtein}
  name: kubernetes
clusters:
- cluster: {server: 'https://k8sapi.apps.tremolo.io'}
  name: kubernetes
users:
- name: mboorshtein
  user:
    auth-provider:
      config: {client-id: kubernetes, id-token: XXXXX,
        idp-issuer-url: 'https://XXXXX/auth/idp/k8sIdp', refresh-token: XXXXXX}
      name: oidc
```

I think the issue is its being output as JSON instead of YAML.  This change doesn't work with the Java API OR `kubectl` and I need to reset my context manually.  Once I'm done with #855 i'll do a PR for this.
