### ISSUE TITLE
Config loading doesn't handle servers w/o http(s)

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#88]
When loading a config that looks like:

```yaml
apiVersion: v1
clusters:
- cluster:
    server: "192.168.1.135:8001"
  name: "nuc"
```

Connection requests fail, because there is no protocol for the URL.

However `kubectl` works properly. We should add a prefix if it is missing.
