### ISSUE TITLE
How to create custom object with a provided yaml spec?

### ISSUE THREAD

**Issue by dbrat43** [kubernetes-client/java#995]
Hi,

I am trying to dynamically create a namespaced custom object using the documentation provided here: https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/CustomObjectsApi.md#createNamespacedCustomObject

When attempting to pass in my json body as a String into the method, I get the following json parse error:

```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the object provided is unrecognized (must be of type NetworkPolicy): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string \"json:\\\"apiVersion,omitempty\\\"\"; Kind string \"json:\\\"kind,omitempty\\\"\" } (227b5c6e20205c2261706956657273696f6e5c223a205c2270726f6a6563 ...)","reason":"BadRequest","code":400}
```

This is my helper method that I'm using to call the CustomObjectsApi:
```java
public Object createKubernetesCustomObject(final String group, final String version, final String namespace, final String plural, final String resourceYaml) throws KubernetesClientException {

	log.info("Received request for namespace: {}, and resource yaml: {} for create kubernetes custom object", namespace, resourceYaml);
	try {

		Object customObject = customObjectsApi.createNamespacedCustomObject(group, version, namespace, plural, resourceYaml, null, null, null);
		return customObject;

	} catch (ApiException e) {

		log.error("Kubernetes ApiException while creating service with code: {}, response body: {}, response headers: {}. Possible error: {}",
				e.getCode(), e.getResponseBody(), e.getResponseHeaders(), K8S_API_ERROR_MESSAGE, e);
		throw new KubernetesClientException(CREATE_SERVICE_FAILURE);
	} catch (Exception e) {

		log.error("Exception while creating a service. Possible error: {}", K8S_RESOURCE_ERROR_MESSAGE, e);
		throw new KubernetesClientException(CREATE_SERVICE_FAILURE);
	}
}
```
This is the sample json that I'm attempting to create an object with:
```json
{
  "apiVersion": "projectcalico.org/v3",
  "kind": "NetworkPolicy",
  "metadata": {
    "name": "default.spark-shared-network-policy",
    "namespace": "my-namespace"
  },
  "spec": {
    "tier": "default",
    "selector": "fleet == 'spark-cluster'",
    "types": [
      "Egress"
    ],
    "egress": [
    {
      "action": "Allow",
      "protocol": "TCP",
      "destination": {
        "nets": [
          "9.9.9.9/32"
        ],
        "ports": [
          50070,
          50470
        ]
      }
    }
    ]
  }
}
```

I also attempted to pass in the below yaml itself, however I got the same error as above:
```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: default.spark-shared-network-policy
  namespace: my-namespace
spec:
  tier: default
  selector:
    fleet == 'spark-cluster'
  types:
    - Egress
  egress:
    - action: Allow 
      protocol: TCP
      destination:
        nets:
          - 9.9.9.9/32
        ports:
          - 50070
          - 50470
```

We are using the Kubernetes client library to generate Kube-native objects in the same class without any issues and I am confident that my json does not have any syntax issues, so I have the following questions:
* Am I calling the createNamespacedCustomObject() method correctly?
* Am I passing in my String json body into the object body correctly, or should I be using a different object to make it work?
* Is there anything else that I'm missing Java-wise?
